# Generated by Django 4.0.5 on 2022-06-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_resume_current_resume_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
