# Generated by Django 4.0.5 on 2022-06-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_resume_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(default='ScottOsteenResume', max_length=100),
        ),
    ]
