# Generated by Django 4.0.6 on 2022-07-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_techtype_technology_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='visual_aids',
            field=models.ManyToManyField(to='main.visualaid'),
        ),
    ]
