# Generated by Django 4.0.6 on 2022-07-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_visualaid_project_visual_aids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='visual_aids',
            field=models.ManyToManyField(blank=True, to='main.visualaid'),
        ),
    ]
