# Generated by Django 3.2.8 on 2021-10-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('html', models.CharField(max_length=30)),
                ('relevance', models.IntegerField()),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('html', models.CharField(max_length=30)),
                ('relevance', models.IntegerField()),
                ('short_desc', models.CharField(max_length=280)),
                ('picture', models.ImageField(upload_to='')),
                ('technologies', models.ManyToManyField(to='main_app.Technology')),
            ],
        ),
    ]
