# Generated by Django 3.2.8 on 2021-10-31 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211030_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
