# Generated by Django 3.2.8 on 2021-10-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_project_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='html',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='technology',
            name='html',
            field=models.TextField(),
        ),
    ]
