# Generated by Django 3.2.8 on 2021-11-01 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20211031_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='html',
        ),
    ]
