# Generated by Django 3.2.8 on 2021-11-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_technology_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='html',
            field=models.CharField(max_length=50),
        ),
    ]
