# Generated by Django 3.2.8 on 2021-11-05 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_project_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='name',
            new_name='type',
        ),
    ]
